version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: medecine_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pharmacy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: express_backend
    restart: always
    working_dir: /app
    environment:
      APP_URL: http://localhost:3000
      NODE_ENV: development
      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PWD: root
      APP_DB: pharmacy_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["npm", "run", "start"]

volumes:
  mysql_data: